myname=input("what's your name?:")
myage=input("how old are you?:")
print("Gee that's too old")
college=input("do you like your college?")
print("ofcourse, you do")
print()
print("what's my name:")
print("myname")
print("what's my age:")
print("myage")